spring:
  application:
    name: library

  datasource:
    url: jdbc:postgresql://postgres.jiicutaazzmkytwukwum:Ahmed@2002##@aws-0-us-east-1.pooler.supabase.com:6543/library
    username: ahmed
    password: Ahmed@2002##

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

server:
  port: 3000
